PHOTOX/ABIN

.github/workflows/gfortran.yml
.gitignore
Makefile
README.md
abin.F90
codecov.yml
pre-push.hook
random.f90

Setup code coverage using Codecov.io

---

UTILS/analyze_movie.f90

Used for analyzing dihedrals between 0°--360° instead of -180° -- 180°.
Useful for dihedrals in anti conformation so that time series and distributions are continuous.

Fix -shiftdih option in analyze_movie

---

force_tera.F90

This changed was lying in my ARGON repo for a while so I don't remember the context fully,
but apparently I had some issues with TeraChem-MPI interface.
Not sure if this solved the actual issue, but it certainly does not hurt to have it.
We will need to do a thorough testing of this before we compile and release  the new ABIN binary on ARGON.

Harden TC-MPI connection (handle empty port case)

---

.gitignore
Makefile
TESTS/test.sh
configure
init.F90

Incorrect parameter passed to test.sh. I also added a lot of TODO comments for future improvements/cleanup around Makefile.
This type of problem will be caught once we include PLUMED in Github Actions build.

Fix Makefile for Plumed

---

.github/codecov_bash_uploader.sh
.github/workflows/gfortran.yml
Makefile
README.md
codecov.yml
src/Makefile
src/README.md
water_potentials/Makefile

- Codecov reports with GFortran 8 and 9 were crashing because we were not setting the correct 'gcov' version.
- Some caches were not used correctly.
The GA config is getting a bit unwieldy. :-(
- GA: Pin Ubuntu version to 18.04:
Github will soon switch it's 'ubuntu-latest'
runner to 'ubuntu-20.04' and we're not ready:
1. Some tests are failing with minor numerical differences on 20.04
Hopefully this get's solved with #27.
2. Some jobs in GFortran CI config now rely on the fact
that the default GCC/GFortran version is 7. We'll need to make that explicit
if we want to switch to 20.04. We want to keep the default version = 7
since that's the one we're using on the PHOTOX clusters.
3. Given our ancient Linux versions on PHOTOX clusters,
it probably makes sense to stick to 18.04 for now.
(and …

Tweaks and fixes for GA and Codecov configs

---

.github/workflows/gfortran.yml
README.md
dev_scripts/install_mpich.sh
tests/REMD/test.sh

Apparently, GCC-8 has been removed from the
Ubuntu-18.04 base image in favour of GCC-10
so we need to adjust.
We still use GCC-7 since this is what is available
on PHOTOX clusters. That's also why we cannot switch
to Ubuntu-20.04 image as it only provides GCC-9/10
I also needed to tweak the FFLAGS for MPI compilation
with GCC-10. The new GFortran does not like when different
types are passed into the same functions (which is typical
for MPI_Send/MPI_Recv).
Lastly, I tried to fix the misbehaving Zenodo badge in README.
NOTE: The Codecov changes here correspond to the previous PR (TC-MPI), since the merge on master failed the tests.

Fix GitHub CI

---

dev_scripts/install_mpich.sh
interfaces/ORCA/r.orca
src/tera_mpi_api.F90
tests/test_tc_server_utils.sh
utils/r.abin
utils/r.terabin

- move code into BASH functions for better readability
- automatically exit on error for better debugging/robustnesss
- use rsync instead of cp for safer and faster sync from scrdir
- `r.terabin`: By default do not use `hydra_nameserver`

Refactor r.abin and r.terabin

---

dev_scripts/setup_dev_environment.sh
dev_scripts/setup_vim.sh
src/gle.F90
src/init.F90
src/transform.F90
tests/REMD/test.sh
water_potentials/Makefile

These are all ugly hacks for now, but I don't have time to fix these things properly for now.
Long term we need to get rid of all GNU/GCC-specific stuff altogether.

Fix compilation with ifort

---

LICENSE
Makefile
src/Makefile
src/abin.F90
src/error.F90
src/fftw_interface.F90
src/force_cp2k.F90
src/force_terash.F90
src/gle.F90
src/init.F90
src/modules.F90
src/plumed.F90
src/remd.F90
src/surfacehop.F90
src/tera_mpi_api.F90
src/transform.F90
src/utils.F90
tests/PILE/input.in
tests/WITHOUT_CP2K/ERROR.ref
tests/WITHOUT_FFTW/ERROR.ref
tests/WITHOUT_MPI/ERROR.ref
tests/WITHOUT_PLUMED/ERROR.ref
unit_tests/Makefile
unit_tests/test_fftw.pf
unit_tests/test_plumed.pf
unit_tests/test_utils.pf
unit_tests/throw_with_pfunit.F90

Here we tentatively refactor the error handling in ABIN, with the ultimate goal of replacing `abinerror`. 
The main purpose of this refactor is to allow the unit tests to test for error conditions. This is currently not possible since calling `abinerror()` unconditionally stops the program, thus disrupting the test suite. To solve that we add a bit of misdirection in `src/error.F90`. Essentially, we allow pFUnit to swap out our error handler subroutine with its own, which then allows checking assertions in unit tests. This swapping occurs via the `set_error_method` in `unit_tests/throw_with_pfunit.F90`.
The new default error handler is called `fatal_error()` and should be used instead of `abinerror`. I converted only a couple of instance for now, and if this all work, I will convert the …

Refactor error handling

---

dev_scripts/install_pfunit.sh

pFunit build started to fail with internal compiler error for GCC-7, see details in 
https://github.com/Goddard-Fortran-Ecosystem/pFUnit/issues/274#issuecomment-975740321

Pin pFUnit version

---

CONTRIBUTING.md
Makefile
src/Makefile
src/cmdline.F90
src/compile_info.F90
src/estimators.F90
src/force_bound.F90
src/force_mm.F90
src/forces.F90
src/gle.F90
src/init.F90
src/landau_zener.F90
src/nosehoover.F90
src/potentials.F90
src/remd.F90
src/sh_integ.F90
src/surfacehop.F90
src/transform.F90
src/utils.F90
src/vinit.F90
tests/CMDLINE/test.sh
utils/analyze_movie.f90

Plus some minor stuff:
- take date/time from preprocessor
- print compiler version and options for all compilers.
This works with Intel >=2018 and Gfortran >= 4.6  Since Intel 2017 currently cannot compile ABIN with MPI, I think it is fine to say we partly suppport Intel 2018 and up.
- change `sqrt` to `dsqrt`.
Apparently, in new compilers this probably/hopefully does not matter, as `sqrt` seems to adapt to its input precision.
Tested with the following program, compiled with gfortran 7.3.0, 4.8, 5.6 and ifort 18.0.2.
```fortran
program test_sqrt
real(8) :: r = 4.0D0
print *, r, sqrt(r), dsqrt(r)
print *, sqrt(4.0), sqrt(4.0D0), dsqrt(4.0D0)
end program
```
Output:
```
4.0000000000000000        2.0000000000000000    2.0000000000000000
2.00000000       2.0000000000000000 …
```

Support -V/--version command line options.

---

.github/workflows/gfortran.yml
configure
src/Makefile
src/constants.F90
src/error.F90
src/fftw_interface.F90
src/files.F90
src/fortran_interfaces.F90
src/init.F90
src/modules.F90
src/random.F90
src/surfacehop.F90
src/tera_mpi_api.F90
src/transform.F90
unit_tests/.gitignore
unit_tests/Makefile
unit_tests/test_fftw.pf
unit_tests/test_masses.pf

Adding `-fimplicit-none` to FFLAGS ensures that we always have `implicit none` in our modules and functions.
I fixed one missing `implicit none` (caught an unitialized variable!) and converted one last implicit typing in `random.F90`.
l also moved `mod_const` from `modules.F90` to a separate file `constants.F90` to break circular dependency due to the 'DP' constant. This allowed me reorder compilation of a some files and make 'fatal_error()' accessible to all modules. In general, our goal should be to have one module per file, so while I was in there, I also did the same for `mod_files`.
Other small changes were done to squash compiler warnings. I also did a bit of cleanup in `mass_init` and wrote some unit tests to verify this functionality (especially user defined masses code was messy …

Ensure implicit none via compiler option

---

.github/workflows/gfortran.yml
src/Makefile
src/abin.F90
src/en_restraint.F90
src/force_tera.F90
src/force_terash.F90
src/init.F90
src/mpi_wrapper.F90
src/remd.F90
src/tera_mpi_api.F90
src/water.F90
tests/REMD/input.in
tests/REMD/input.in2
tests/REMD/input.in3
tests/REMD/test.sh
tests/TERAPI-FAILS/ABIN_ERROR4.ref
tests/TERAPI-FAILS/ABIN_ERROR8.ref
tests/TERAPI-FAILS/test.sh

The idea here is to centralize certain calls to MPI library in one place, with proper error handling.
This should reduce the amount of `#ifdef USE_MPI` throughout the codebase.
We also encapsule MPI initialization and finalization, and provide helper functions for error handling.

Create MPI wrapper module

---

src/mpi_wrapper.F90
src/remd.F90
tests/REMD/ERROR.ref
tests/REMD/test.sh

Follow-up on #97. Do not call `MPI_Abort()` for TC-MPI interface, since it screws up code coverage for some reason (very strange :scream:), and it is not needed anyway since we only have one MPI process.
Add a test case for failing REMD.
Also minor cleanup in `remd_init()`.

Fix the code coverage for mpi error paths

---

.github/workflows/gfortran.yml
src/plumed.F90
tests/PLUMED/test.sh
unit_tests/Makefile
unit_tests/test_plumed.pf

Closes #83.
Plumed 2.8 fails one unit test and the METAD test because Plumed started using stretched gaussians, which leads to numerical differences.
See https://github.com/plumed/plumed2/issues/420 and https://github.com/plumed/plumed2/pull/757. As a quick fix for our test suite, we can set env variable PLUMED_DP2CUTOFF_NOSTRETCH before the linking step.

GHA: support Plumed 2.8

---

src/landau_zener.F90

Fixes #74
I am surprised that this has worked, and also that older compiler versions didn't catch this mistake.
@suchanj please take a look as this is your code.

Fix intent in lz_restin

---

src/analysis.F90

Explicitly specifying a format for floats in `read` statements apparently leads to runtime errors if the number is in a different format (e.g. in old restart file) so we cannot use it.

Fix restart from old restart files

---

interfaces/MNDO-LZ/mndo.inp
interfaces/MNDO-LZ/r.mndo-lz

This interface allows to run LZSH simulations with the OMx methods in the MNDO package. Tested for OM2, OM3, ODM2 and ODM3. Works only for states with the same multiplicity, ISC cannot be described. Contributions Michal Belina and Jan Polena.

Interface for Landau-Zener SH with MNDO program

---

.github/workflows/gfortran.yml
codecov.yml
src/force_mm.F90
src/nosehoover.F90
tests/INIT/test.sh
unit_tests/Makefile
unit_tests/test_mm.pf
unit_tests/test_spline.pf

Github actions removed the runner for Ubuntu 18.04, which is why ABIN CI tests were not running. Here I update all jobs to Ubuntu 20.04. 
~~This unfortunately means we can no longer test with gfortran-7.
@JanosJiri for your PRs, please always manually test on Argon or Neon with GCC 7.3.~~
EDIT: I figured out how to install GCC-7 so we're good here.

GHA: Update Ubuntu version to 20.04

---

src/fortran_interfaces.F90
src/init.F90
src/tera_mpi_api.F90
src/utils.F90
tests/TERAPI-FAILS/input.in.valid
tests/TERAPI-FAILS/input.in1
tests/TERAPI-FAILS/input.in2
tests/TERAPI-FAILS/input.in4
tests/TERAPI-FAILS/input.in5
tests/TERAPI-FAILS/input.in6
tests/TERAPI-FAILS/input.in7
tests/TERAPI-FAILS/input.in8

When communicating with TeraChem via MPI, we're sleeping for 50 miliseconds. Otherwise, ABIN busy-waits and consumes the whole CPU.
Here is a better implementation of this behaviour, using the system call function `usleep`, instead of calling to shell. 
Closes #163

Use usleep to wait for TeraChem

---

fprettify/__init__.py
tests/TERAPI-FAILS/ABIN_ERROR4.ref
tests/TERAPI-FAILS/test4.sh

+ fix small issue in fprettify caught by the ruff linter (although it does not seem to have impacted us, and I am not sure how to trigger a bug)

Fix intel test

---

interfaces/TERACHEM/r.terachem
src/force_abin.F90
src/init.F90
utils/abin-randomint.f90

The Amber MPI interface in TC was removed in 2021. We've used this interface for ground state MD.
Instead, we now have the TCPB interface, but still in an experimental stage. Therefore, for now we bring back the simple file interface as a quick hassle free way to run MD with TeraChem.
WARNING: For small / medium sized molecules, you will lose a lot of time during repeated GPU initialization!

Bring back TeraChem file interface

---

.github/workflows/gfortran.yml

Let's see if this helps with the success rate of Codecov upload.

Bump Codecov action to v4

---

utils/create_trajectories.sh

Mostly cosmetic changes and cleanup.
One functional change: It is now possible to specify `submit_command=bash` if the trajectories are to be run directly on a machine (e.g. Squirrel or Hamilton nodes) instead of submitting to queing system. In this case, the launch script `r.abin` doesn't need to be provided in the template directory.

Cleanup create_trajectories.sh with shellcheck

---

.github/workflows/gfortran.yml
autoformat.py
src/h2o_cvrqd.f

You can now run the formatter with uv or pipx directly as:
`uv run autoformat.py`
Python dependencies will be installed automatically.
TODO: Document this in `CONTRIBUTING.md`

formatter: Add inline python requirements ala PEP 722

---

src/abin.F90
src/force_abin.F90
src/init.F90
src/landau_zener.F90
src/surfacehop.F90
tests/test.sh

Another small bug (or perhaps rather a missing feature) found by Jack Taylor. Sometimes we want to calculate more electronic state (e.g. to make CASSCF more stable) but do not want to consider them in hoping algorithms. A prototypical example is simulating ethylene with SA3-CAS(2,2) starting from S1 and wanting to prevent hops to S2.
Also a minor refactoring to make more LZ stuff private to the `mod_lz` module.

Add 'ignore_state' in Launda-Zener hopping

---

.github/workflows/gfortran.yml

Hoping to make things less confusing by having a separate job that has `-check=all` and other runtime  check flags.

CI: Add separate debug build with GCC 13

---

interfaces/ORCA/orca_template.inp
interfaces/ORCA/r.orca

Similar cleanup as in #179 for DFTB+ interface.
The idea here is to make the `ORCA/r.orca` script more readable and robust.
The logic is separated into two main functions: `prepare_orca_inputs` and `extract_energy_gradient`.
This hopefully makes the script flow clearer, because at the bottom we now just have
```bash
prepare_orca_input
cd "$WORKDIR" || exit 2
if ! $ORCAEXE "$input" &> "$input.out"; then
echo "ERROR: ORCA calculation failed. See Orca output file $WORKDIR/$input.out"
exit 2
fi
extract_energy_and_gradients "../../engrad.dat.$ibead"
```
The other big change here is that the ORCA input is now specified in a separate file `orca_template.inp`.  The idea here is to separate the ORCA input so that the user doesn't need to mess with the `r.orca` script. To reviewers: Please let me …

Orca interface cleanup

---

src/surfacehop.F90

`ignore_state` was not operational for `couplings='baeck-an'` since this was natively done in `set_tocalc()`.

Ignoring BA sigma for ignor_state

---

fortitude.toml
src/arrays.F90
src/compile_info.F90
src/constants.F90
src/estimators.F90
src/fftw_interface.F90
src/files.F90
src/forces.F90
src/h2o_cvrqd.f
src/init.F90
src/modules.F90
src/pbc.F90

A new version of fortitude linter has been released, with lot's more configuration options:
https://github.com/PlasmaFAIR/fortitude/releases/tag/v0.7.0
This will allow us to run it in CI, I'll add it in a follow-up PR.

Update fortitude linter to v0.7

---

CITATION.cff
interfaces/CP2K/r.cp2k
interfaces/GAUSSIAN/r.gaussian
interfaces/MOLPRO/r.molpro
interfaces/MOPAC/r.mopac
interfaces/ORCA/r.orca
interfaces/QCHEM/r.qchem
interfaces/TERACHEM/r.terachem
interfaces/TURBO/r.turbo
src/compile_info.F90
src/error.F90
src/init.F90

Re: Authorship, I went through Git history so I don't forget anybody, but obviously other people contributed that might not be in the history directly --- please let me know!
(commit count doesn't matter and is not necessarily indicative of anything)
```
❯ git shortlog -e -s -n
322  Daniel Hollas <hollasd@vscht.cz>
147  Daniel Hollas <danekhollas@gmail.com>
32  Daniel Hollas <daniel.hollas@bristol.ac.uk>
24  Jiri Suchan <ji.suchan@seznam.cz>
22  Jiri Suchan <suchanj@vscht.cz>
15  suchanj <ji.suchan@seznam.cz>
6  Daniel Hollas <hollas@vscht.cz>
5  Daniel Hollas <hollasd@vscht.com>
5  JanosJiri <88504448+JanosJiri@users.noreply.github.com>
5  Jiří Janoš <88504448+JanosJiri@users.noreply.github.com>
4  Daniel Hollas <daniel.hollas@durham.ac.uk>
3  Stepan Srsen <srsen.stepan@gmail.com>
2 …
```

Preparation for v1.2 release
